name: bench
'on':
  schedule:
    - cron: 0 0 * * *
  push:
    paths:
      - '**.ts'
jobs:
  bare_abc:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: abc
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: abc
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  bare_alosaur:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: alosaur
        run: |-
          deno run --config tsconfig.json -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: alosaur
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main

  bare_deno:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: deno
        run: |-
          deno run -A bare.ts &
          sleep 15 &&
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: deno
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main

  bare_dinatra:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: dinatra
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: dinatra
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  bare_drash:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: drash
        run: |-
          deno run -A bare.ts &
          sleep 10 &&
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: drash
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main

  bare_express:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: express
        run: |-
          npm i
          node bare.js &
          sleep 15 &&
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: express
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main

  bare_fastify:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
      - bare_express
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: fastify
        run: |-
          npm i
          node bare.js &
          sleep 15 &&
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: fastify
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main

  bare_fastro:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
      - bare_express
      - bare_fastify
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: fastro
        run: |-
          deno run -A bare.ts &
          sleep 15 &&
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: fastro
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main

  bare_node:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
      - bare_express
      - bare_fastify
      - bare_fastro
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: node
        run: |-
          node bare.js &
          sleep 15 &&
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: node
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main

  bare_oak:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
      - bare_express
      - bare_fastify
      - bare_fastro
      - bare_node
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: oak
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: oak
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  bare_pogo:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
      - bare_express
      - bare_fastify
      - bare_fastro
      - bare_node
      - bare_oak
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: pogo
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: pogo
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  bare_servest:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
      - bare_express
      - bare_fastify
      - bare_fastro
      - bare_node
      - bare_oak
      - bare_pogo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: servest
        run: |-
          deno run -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: servest
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  bare_mandarinets:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
      - bare_express
      - bare_fastify
      - bare_fastro
      - bare_node
      - bare_oak
      - bare_pogo
      - bare_servest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup nodejs 13
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install Autocannon
        run: npm install -g autocannon
      - name: START
        run: echo "Starting Benchmarks"
      - name: mandarinets
        run: |-
          deno run --config tsconfig.json -A bare.ts &
          sleep 15 && 
          mkdir -p results &&
          autocannon -c 40 -d 10 -j http://localhost:8000 > results/bare.json &&
          kill $!
        working-directory: mandarinets
      - name: END
        run: echo "End Benchmarks"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
  _results:
    runs-on: ubuntu-latest
    needs:
      - bare_abc
      - bare_alosaur
      - bare_deno
      - bare_dinatra
      - bare_drash
      - bare_express
      - bare_fastify
      - bare_fastro
      - bare_node
      - bare_oak
      - bare_pogo
      - bare_servest
      - bare_mandarinets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pull changes from other benchmarks
        run: git pull
      - name: Setup deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Generate README.md
        run: deno run -A --unstable _bench/readme.ts
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: qu4k@users.noreply.github.com
          coauthor_name: qu4k
          branch: main
